/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:da837004-ae3e-48f5-b657-1fc30591e701",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_LYLtWC5WU",
    "aws_user_pools_web_client_id": "310nktc7tc088ncv36bmqcjkds",
    "oauth": {}
};


export default awsmobile;
