/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:6223a412-de5c-41dc-aa58-61c728bd37e3",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_31DfB9rNR",
    "aws_user_pools_web_client_id": "1coqvqan15stpnejl014eu2jpn",
    "oauth": {}
};


export default awsmobile;
